name: Frontend CI/CD (Docker)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - run: |
          docker build \
            --file frontend/Dockerfile \
            --target test \
            --tag frontend-test:${{ github.sha }} \
            frontend
          docker run --rm frontend-test:${{ github.sha }}

  docker_build_and_deploy:
    name: Build, Push & Deploy Frontend
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker build \
            --file frontend/Dockerfile \
            --target prod \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/sample-frontend:latest \
            frontend

      - run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sample-frontend:latest

      - name: Trigger Render deploy
        run: |
          curl -X POST "${{ secrets.FRONTEND_RENDER_DEPLOY_HOOK_URL }}"
